### ISSUE TITLE
Heading levels not distinctive

### ISSUE THREAD

**Issue by lisafast** [gc-proto/health-1#5]
@jmealing , just a reminder that participants seemed to have a hard time distinguishing between H2 and H3 headings. Yet H3s are important to screen reader users. I really notice it on this new page - if there is a better way to make the H3s in the Additives section look more clearly different than the H2s, this is a good page to play with that. 

https://gc-proto.github.io/health-1/scenarioH/services/vaccination-children-2.html

FYI @DK-TBS

**Comment by quidampepin** [comment]
In the specific case of additives, I tried using details/summary instead, since the information for each is not critical for the main task of the page, I believe (and if you really want to know the details for each additive, you can expand). I think it works well in this specific case. 

But this doesn't solve the H2 vs H3 question for other spots.

**Comment by quidampepin** [comment]
BTW I moved additives to the "Vaccines safety and concerns page: https://gc-proto.github.io/health-1/scenarioH/services/vaccination-children-3.html

**Comment by lisafast** [comment]
Thanks @quidampepin - I had a laugh when I saw I was referring to a page that no longer had that content. Agree that details/summary works well for those - and that like you say, it doesn't solve H2 vs H3 for Canada.ca as a whole. 

Actually, it doesn't quite work - moved to new issue. #6

**Comment by jmealing** [comment]
Will work on this, thanks

**Comment by jmealing** [comment]
Custom css is setup and being deployed in zika
